apiVersion: v1
kind: Secret
metadata:
  name: awssecret # Name of the secret
  namespace: default # Namespace of the secret
data:
  providerAccessKeyId: "QUtJQVlZRk5YREtIUExRTk5GQTQ=" # AWS access key id (base64 encoded)
  providerSecretAccessKey: "U3NERnpLTUtWQmZmemdxZk9GZ0trYkJRaGFGN1dDVkJUUUxNYkJQQg==" # AWS secret access key (base64 encoded)
### Alternative data keys are:
# accessKeyId: "pqrstu67890" # AWS access key id (base64 encoded)
# secretAccessKey: "abcdef123456" # AWS secret access key (base64 encoded)
type: Opaque