apiVersion: v1
kind: Service
metadata:
  name: backend-user
spec:
  selector:
    app: backend-user
    app.kubernetes.io/name: backend-user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080