apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
spec:
  selector:
    app: reverseproxy
    app.kubernetes.io/name: reverseproxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080